import type { CategoryProvider } from './categoryProvider.js';

/**
 * Test category provider with a static list of 10 categories
 */
export class StaticCategoryProvider implements CategoryProvider {
  private readonly categories = [
    'Animals',
    'Foods',
    'Countries',
    'Famous People',
    'Movies',
    'Sports',
    'Colors',
    'Vegetables',
    'Cities',
    'Brands',
    'Occupations',
    'Things That Are Hot',
    'Things That Are Cold',
    'Things in a Kitchen',
    'Things in a Bathroom',
    'Things Found in a Park',
    'Musical Instruments',
    'Types of Clothing',
    'School Subjects',
    'Fruits',
    'Parts of the Body',
    'TV Shows',
    'Video Games',
    'Holidays',
    'Types of Weather',
    'Things That Fly',
    'Things You Find at the Beach',
    'Tools',
    'Desserts',
    'Drinks',
    'Book Titles',
    'Cartoon Characters',
    'Superheroes',
    'Things in the Sky',
    'Things That Are Round',
    'Breakfast Foods',
    'Pizza Toppings',
    'Ice Cream Flavors',
    'Types of Dance',
    'Board Games',
    'Things in a Bedroom',
    'Hobbies',
    'Things That Are Green',
    'Things That Smell Bad',
    'Things You Plug In',
    'Furniture',
    'Things in a Garage',
    'Restaurant Names',
    'Dinosaurs',
    'Car Brands',
    'Things at a Birthday Party',
    'Apps',
    'Sandwiches',
    'Candy',
    'Reptiles',
    'Types of Trees',
    'Things That Bounce',
    'Reasons to Call 911',
    'Things in a Refrigerator',
    'Magazines',
    'Things That Are Sticky',
    'Things You Find in a Wallet',
    'Things That Make You Laugh',
    'Things in a Gym',
    'Excuses for Being Late',
    'Cereal Brands',
    'Things That Are Soft',
    'Mythical Creatures',
    'Things You Wear on Your Head',
    'Types of Pasta',
    'Things in a Backpack',
    'Famous Athletes',
    'Things That Are Loud',
    'Things You Do at a Sleepover',
    'Types of Cheese',
    'Things in Space',
    'Flower Names',
    'Things That Are Shiny',
    'Bad Habits',
    'Things You Find Underground',
    'Types of Soup',
    'Things at a Wedding',
    'Items in a First Aid Kit',
    'Things You See at a Zoo',
    'Types of Bread',
    'Things That Are Yellow',
    'YouTube Channels',
    'Things That Melt',
    'Spices',
    'Things in a Classroom',
    'Fast Food Restaurants',
    'Things That Are Heavy',
    'Reasons to Celebrate',
    'Types of Music',
    'Things You Find at a Carnival',
    'Things That Are Scary',
    'College Majors',
    'Things in a Hotel Room',
    'Condiments',
    'Things You Do Before Bed',
    'Insects',
    'Things That Are Blue',
    'Household Chores',
    'Things at a Concert',
    'Sauces',
    'Things You Shouldn\'t Touch',
  ];

  getCategories(count: number): string[] {
    // Shuffle and return requested number of categories
    const shuffled = [...this.categories].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, Math.min(count, this.categories.length));
  }

  getName(): string {
    return 'Test Category Provider';
  }
}
